//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShockingMomentsInSports.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Moment
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Sport { get; set; }

        [Display(Name = "League/Category")]
        public string LeagueOrCategory { get; set; }
        public string Event { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Date { get; set; }
        public string Description { get; set; }

        [Display(Name = "YouTube Video")]
        public string YouTubeVideo { get; set; }
    }
}
